version: '3'

services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: ./services
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongodb
  #   networks: 
  #     - tic_network
  nginx:
    image: nginx:latest
    ports:
      - "5000:5000"  # Exponer el puerto 5000 para NGINX
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Montar la configuración de NGINX
    depends_on:
      - assetservice
      - layerservice
    networks: 
      - tic_network

  assetservice:
    build:
      context: ./services/AssetService  # Ruta al Dockerfile de AssetService
    container_name: assetservice
    env_file:
      - ./services/.env
    depends_on:
      - mongodb
    networks: 
      - tic_network
    environment:
      - FLASK_ENV=development

  layerservice:
    build:
      context: ./services/LayerService  # Ruta al Dockerfile de LayerService
    container_name: layerservice
    env_file:
      - ./services/.env
    depends_on:
      - mongodb
    networks: 
      - tic_network
    environment:
      - FLASK_ENV=development

  # frontend:
  #   build:
  #     context: ./app
  #   ports:
  #     - "3000:3000"
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - tic_network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    networks: 
      - tic_network

networks:
  tic_network:
    external: true