
services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: ./services
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongodb
  #   networks: 
  #     - tic_network
  assetservice:
    build:
      context: ./services/AssetService  # Ruta hacia el Dockerfile del microservicio
    container_name: assetservice
    ports:
      - "5000:5000"  # Exponiendo el puerto donde correrá AssetService
    env_file:
      - ./services/AssetService/.env
    depends_on:
      - mongodb
    networks: 
      - tic_network
    environment:
      - FLASK_ENV=development

  # frontend:
  #   build:
  #     context: ./app
  #   ports:
  #     - "3000:3000"

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - tic_network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    networks: 
      - tic_network

networks:
  tic_network:
    external: true
